AWSTemplateFormatVersion: 2010-09-09


Resources:
  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: AWSEC2Backups
        BackupPlanRule:
          -
            RuleName: DailyBackups
            TargetBackupVault: Default
            ScheduleExpression: "cron(01 04 ? * * *)"
            StartWindowMinutes: 120
            CompletionWindowMinutes: 1200
            Lifecycle:
              DeleteAfterDays: 7
          -
            RuleName: WeeklyExpire35Days
            TargetBackupVault: Default
            ScheduleExpression: "cron(01 12 ? * 1 *)"
            StartWindowMinutes: 120
            CompletionWindowMinutes: 1200
            Lifecycle: 
              DeleteAfterDays: 35
      BackupPlanTags: { Key: BackupPlan, Value: CDPDev-Standard}

  TagBasedBackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupSelection:
        SelectionName: BackupTagsEC2
        IamRoleArn: !GetAtt  AWSBackupRole.Arn
        ListOfTags:
         -
           ConditionType: "STRINGEQUALS"
           ConditionKey: "Backup"
           ConditionValue: "Standard"
      BackupPlanId: !Ref BackupPlan



  AWSBackupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ "AWSBackup", "EC2", !Ref 'AWS::StackName', 'role' ] ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: backup.amazonaws.com
          Action: sts:AssumeRole

  AWSBackupBackupPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Join [ "-", [ "AWSBackup", !Ref 'AWS::StackName', 'policy' ] ]
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Action:
          - dynamodb:DescribeTable
          - dynamodb:CreateBackup
          Resource: arn:aws:dynamodb:*:*:table/*
          Effect: Allow
        - Action:
          - dynamodb:DescribeBackup
          - dynamodb:DeleteBackup
          Resource: arn:aws:dynamodb:*:*:table/*/backup/*
          Effect: Allow
        - Effect: Allow
          Action:
          - rds:AddTagsToResource
          - rds:ListTagsForResource
          - rds:DescribeDBSnapshots
          - rds:CreateDBSnapshot
          - rds:CopyDBSnapshot
          - rds:DescribeDBInstances
          - rds:CreateDBClusterSnapshot
          - rds:DescribeDBClusters
          - rds:DescribeDBClusterSnapshots
          - rds:CopyDBClusterSnapshot
          Resource: "*"
        - Effect: Allow
          Action:
          - rds:DeleteDBSnapshot
          - rds:ModifyDBSnapshotAttribute
          Resource:
          - arn:aws:rds:*:*:snapshot:awsbackup:*
        - Effect: Allow
          Action:
          - rds:DeleteDBClusterSnapshot
          - rds:ModifyDBClusterSnapshotAttribute
          Resource:
          - arn:aws:rds:*:*:cluster-snapshot:awsbackup:*
        - Effect: Allow
          Action:
          - storagegateway:CreateSnapshot
          - storagegateway:ListTagsForResource
          Resource: arn:aws:storagegateway:*:*:gateway/*/volume/*
        - Effect: Allow
          Action:
          - ec2:CopySnapshot
          Resource: arn:aws:ec2:*::snapshot/*
        - Effect: Allow
          Action:
          - ec2:CopyImage
          Resource: "*"
        - Effect: Allow
          Action:
          - ec2:CreateTags
          - ec2:DeleteSnapshot
          Resource: arn:aws:ec2:*::snapshot/*
        - Effect: Allow
          Action:
          - ec2:CreateImage
          - ec2:DeregisterImage
          Resource: "*"
        - Effect: Allow
          Action:
          - ec2:CreateTags
          Resource: arn:aws:ec2:*:*:image/*
        - Effect: Allow
          Action:
          - ec2:DescribeSnapshots
          - ec2:DescribeTags
          - ec2:DescribeImages
          - ec2:DescribeInstances
          - ec2:DescribeInstanceAttribute
          - ec2:DescribeInstanceCreditSpecifications
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribeElasticGpus
          - ec2:DescribeSpotInstanceRequests
          Resource: "*"
        - Effect: Allow
          Action:
          - ec2:ModifySnapshotAttribute
          - ec2:ModifyImageAttribute
          Resource: "*"
          Condition:
            'Null':
              aws:ResourceTag/aws:backup:source-resource: 'false'
        - Effect: Allow
          Action:
          - backup:DescribeBackupVault
          - backup:CopyIntoBackupVault
          Resource: arn:aws:backup:*:*:backup-vault:*
        - Effect: Allow
          Action:
          - backup:CopyFromBackupVault
          Resource: "*"
        - Action:
          - elasticfilesystem:Backup
          - elasticfilesystem:DescribeTags
          Resource: arn:aws:elasticfilesystem:*:*:file-system/*
          Effect: Allow
        - Effect: Allow
          Action:
          - ec2:CreateSnapshot
          - ec2:DeleteSnapshot
          - ec2:DescribeVolumes
          - ec2:DescribeSnapshots
          Resource:
          - arn:aws:ec2:*::snapshot/*
          - arn:aws:ec2:*:*:volume/*
        - Action: kms:DescribeKey
          Effect: Allow
          Resource: "*"
        - Action: kms:CreateGrant
          Effect: Allow
          Resource: "*"
          Condition:
            Bool:
              kms:GrantIsForAWSResource: 'true'
        - Action:
          - kms:GenerateDataKeyWithoutPlaintext
          Effect: Allow
          Resource: arn:aws:kms:*:*:key/*
          Condition:
            StringLike:
              kms:ViaService:
              - ec2.*.amazonaws.com
        - Action:
          - tag:GetResources
          Resource: "*"
          Effect: Allow
        - Effect: Allow
          Action:
          - ssm:CancelCommand
          - ssm:GetCommandInvocation
          Resource: "*"
        - Effect: Allow
          Action: ssm:SendCommand
          Resource:
          - arn:aws:ssm:*:*:document/AWSEC2-CreateVssSnapshot
          - arn:aws:ec2:*:*:instance/*
        - Action: fsx:DescribeBackups
          Effect: Allow
          Resource: arn:aws:fsx:*:*:backup/*
        - Action: fsx:CreateBackup
          Effect: Allow
          Resource:
          - arn:aws:fsx:*:*:file-system/*
          - arn:aws:fsx:*:*:backup/*
        - Action: fsx:DescribeFileSystems
          Effect: Allow
          Resource: arn:aws:fsx:*:*:file-system/*
        - Action: fsx:ListTagsForResource
          Effect: Allow
          Resource: arn:aws:fsx:*:*:file-system/*
        - Action: fsx:DeleteBackup
          Effect: Allow
          Resource: arn:aws:fsx:*:*:backup/*
      Roles:
      - Ref: AWSBackupRole


  AWSBackupRestorePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Join [ "-", [ "AWSRestore", !Ref 'AWS::StackName', 'policy' ] ]
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Action:
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
          - dynamodb:DescribeTable
          Resource: arn:aws:dynamodb:*:*:table/*
          Effect: Allow
        - Action:
          - dynamodb:RestoreTableFromBackup
          Resource: arn:aws:dynamodb:*:*:table/*/backup/*
          Effect: Allow
        - Effect: Allow
          Action:
          - ec2:CreateVolume
          - ec2:DeleteVolume
          Resource:
          - arn:aws:ec2:*::snapshot/*
          - arn:aws:ec2:*:*:volume/*
        - Effect: Allow
          Action:
          - ec2:DescribeSnapshots
          - ec2:DescribeVolumes
          Resource: "*"
        - Effect: Allow
          Action:
          - storagegateway:DeleteVolume
          - storagegateway:DescribeCachediSCSIVolumes
          - storagegateway:DescribeStorediSCSIVolumes
          Resource: arn:aws:storagegateway:*:*:gateway/*/volume/*
        - Effect: Allow
          Action:
          - storagegateway:DescribeGatewayInformation
          - storagegateway:CreateStorediSCSIVolume
          - storagegateway:CreateCachediSCSIVolume
          Resource: arn:aws:storagegateway:*:*:gateway/*
        - Effect: Allow
          Action:
          - storagegateway:ListVolumes
          Resource: arn:aws:storagegateway:*:*:*
        - Effect: Allow
          Action:
          - rds:DescribeDBInstances
          - rds:DescribeDBSnapshots
          - rds:ListTagsForResource
          - rds:RestoreDBInstanceFromDBSnapshot
          - rds:DeleteDBInstance
          - rds:AddTagsToResource
          - rds:DescribeDBClusters
          - rds:RestoreDBClusterFromSnapshot
          - rds:DeleteDBCluster
          Resource: "*"
        - Effect: Allow
          Action:
          - elasticfilesystem:Restore
          - elasticfilesystem:CreateFilesystem
          - elasticfilesystem:DescribeFilesystems
          - elasticfilesystem:DeleteFilesystem
          Resource: arn:aws:elasticfilesystem:*:*:file-system/*
        - Action: kms:DescribeKey
          Effect: Allow
          Resource: "*"
        - Action:
          - kms:Decrypt
          - kms:Encrypt
          - kms:GenerateDataKey
          - kms:ReEncryptTo
          - kms:ReEncryptFrom
          Effect: Allow
          Resource: "*"
          Condition:
            StringLike:
              kms:ViaService:
              - dynamodb.*.amazonaws.com
              - ec2.*.amazonaws.com
              - elasticfilesystem.*.amazonaws.com
              - rds.*.amazonaws.com
        - Action: kms:CreateGrant
          Effect: Allow
          Resource: "*"
          Condition:
            Bool:
              kms:GrantIsForAWSResource: 'true'
        - Action:
          - ec2:RunInstances
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:TerminateInstances
          Effect: Allow
          Resource: arn:aws:ec2:*:*:instance/*
        - Action:
          - fsx:CreateFileSystemFromBackup
          Effect: Allow
          Resource:
          - arn:aws:fsx:*:*:file-system/*
          - arn:aws:fsx:*:*:backup/*
        - Action: fsx:DescribeFileSystems
          Effect: Allow
          Resource: arn:aws:fsx:*:*:file-system/*
        - Action: fsx:DescribeBackups
          Effect: Allow
          Resource: arn:aws:fsx:*:*:backup/*
        - Action:
          - fsx:DeleteFileSystem
          - fsx:UntagResource
          Effect: Allow
          Resource: arn:aws:fsx:*:*:file-system/*
          Condition:
            'Null':
              aws:ResourceTag/aws:backup:source-resource: 'false'
        - Action: ds:DescribeDirectories
          Effect: Allow
          Resource: "*"
      Roles:
      - Ref: AWSBackupRole
