############################################################
# Filename: ECC_S3.yaml

# Version History : 
# v1:  Authored by Kevin Gross for support or feedback reach out at kevin.gross@accenture.com

# Comments:
# 
# 10/2/2020 - KG
# Template desginged to allow account to write to S3 bucket.
# 
# 10/12/2020 - KG
# Adjusted some permissions to allow user to read permissions

############################################################

AWSTemplateFormatVersion: 2010-09-09

Parameters: 

  S3Name: 
    Type: String 
    Description: S3 Bucket ARN for EC2 destination


Resources: 

  S3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ "-", [ !Ref 'AWS::StackName', 'role' ] ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole


  S3Policy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Join [ "-", [  !Ref 'AWS::StackName', 'policy' ] ]
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetBucketTagging
          - s3:GetObjectVersionTagging
          - s3:GetBucketLogging
          - s3:ListBucket
          - s3:GetBucketAcl
          - s3:GetBucketPolicy
          - s3:PutObject
          - s3:PutObjectTagging
          - s3:GetObjectAcl
          - s3:GetEncryptionConfiguration
          - s3:GetObjectTagging
          - s3:GetBucketLocation
          - s3:GetBucketTagging
          - s3:GetObjectVersion
          Resource:
          - !Ref S3Name
          - Fn::Join: ['/', [!Ref S3Name, '*'] ]
        - Effect: Allow
          Action:
          - s3:ListBucket
          - s3:GetObject
          - s3:GetBucketLocation
          Resource:
          - !Ref S3Name
        - Effect: Allow
          Action:
          - s3:GetAccountPublicAccessBlock
          - s3:ListAllMyBuckets
          Resource:
          - "*"
      Roles:
      - Ref: S3Role

Outputs:
  S3RoleName:
    Value: !Ref S3Role
    Description: Name of role

  S3PolicyName:
    Value: !Ref S3Policy
    Description: Policy created for this process

  S3NameARN:
    Value: !Ref S3Name
    Description: ARN for S3 Bucket